# Generated by Django 3.2.3 on 2021-12-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_substitution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Substitution',
        ),
    ]
