# Generated by Django 3.2.3 on 2021-12-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_delete_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='substituted',
            field=models.BooleanField(default=False),
        ),
    ]
