version: '3.7'

services:

  sample:
    container_name: reactjs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/ubuntu/reactjs'
      - '/home/ubuntu/reactjs/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

